version: '3'

services:
  api:
    build:
      context: .
      args:
        - PORT=$PORT
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    ports:
      - $PORT:$PORT
    restart: always
